package router

import (
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"os"
	"personal-finance-api/controllers"
	"personal-finance-api/docs"
)

var r *gin.Engine

func SetupRouter() *gin.Engine {
	r = gin.Default()
	SetupCors()
	SetupAPIRoutes()
	SetupSwagger()
	return r
}

func SetupAPIRoutes() {
	r.POST("/generate", controllers.GeneratePlan)
}

func SetupSwagger() {
	// Swagger config
	docs.SwaggerInfo.Title = "Personal Finance ChatGPT API"
	docs.SwaggerInfo.Description = "Allows users to obtain a financial plan generated by ChatGPT given their situation."
	docs.SwaggerInfo.Version = "0.1.0"
	docs.SwaggerInfo.Host = os.Getenv("HOST_NAME")
	docs.SwaggerInfo.BasePath = "/"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
}

func SetupCors() {

	// TODO Allows all. Should update when in prod/test/local
	//config := cors.DefaultConfig()
	//config.AllowAllOrigins = true
	//router.Use(cors.New(config))
	r.Use(cors.Default())
}
